#!/usr/bin/env bash

set -euo pipefail

UPIA_BIN="/Library/Application Support/Adobe/Adobe Desktop Common/RemoteComponents/UPI/UnifiedPluginInstallerAgent/UnifiedPluginInstallerAgent.app/Contents/MacOS/UnifiedPluginInstallerAgent"
EXTENSION_FILE_NAME="$HOME/Downloads/com.cuttable.extension.zxp"

if [ ! -f "$EXTENSION_FILE_NAME" ]; then
   echo "File $EXTENSION_FILE_NAME does not exist."
   echo "Please ensure that you have downloaded the extension to ~/Downloads/com.cuttable.extension.zxp"
   exit 1;
fi

echo "🧹 Cleaning cuttable extension..."
set +e
"$UPIA_BIN" --remove com.cuttable.extension
set -e

echo "Installing cuttable extension..."
"$UPIA_BIN" --install "$EXTENSION_FILE_NAME"

"$UPIA_BIN" --list all 
echo "Installation complete."
